version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/load_secrets.sh
      timeout: 300
      runas: root

    - location: scripts/build_and_run_docker.sh
      timeout: 600
      runas: root