name: CICD_Prod

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML_PROD }}" | base64 --decode > src/main/resources/application.yml

      - name: Set up ENV
        run: echo "TIME=$(date "+%Y_%m_%d_%H_%M")" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Store secrets in Parameter Store
        run: |
          aws ssm put-parameter --name "/aws/region" --value "${{ secrets.AWS_REGION }}" --type SecureString --overwrite
          aws ssm put-parameter --name "/app/time" --value "${{ env.TIME }}" --type String --overwrite

      - name: Compress code
        run: |
          zip -r code.zip .

      - name: Upload code to S3
        run: |
          aws s3 cp code.zip s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.sha }}.zip

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_GROUP_NAME }} \
            --description "Deployment from GitHub Actions" \
            --revision revisionType=S3,s3Location={bucket=${{ secrets.AWS_S3_BUCKET }},key=${{ github.sha }},bundleType=zip}

      - name: Wait for CodeDeploy Deployment
        run: |
          aws deploy wait deployment-successful --deployment-id ${{ steps.deploy.outputs.deployment-id }}